[build]
    functions = "functions"
    base = "/"
    command = "pnpm build"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[[redirects]]
    from = "/abend-fuer-die-moore-tickets"
    to = "https://example-frame-tickets.com"
    status = 302
    force = true
[[redirects]]
    from = "/abend-fuer-die-moore-wwf"
    to = "https://example-wwf-event.com"
    status = 302
    force = true
[[redirects]]
    from = "/*"
    to = "/"
    status = 200
[build.environment]
  GO_VERSION = "1.19.4"