[build]
    functions = "functions"
    base = "/"
    command = "npm run build"
[build.environment]
    NODE_VERSION = "18"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[[redirects]]
    from = "/abend-fuer-die-moore-tickets"
    to = "/.netlify/functions/utm-track"
    status = 200
    force = true
[[redirects]]
    from = "/abend-fuer-die-moore-wwf"
    to = "/.netlify/functions/wwf-track"
    status = 200
    force = true
[[redirects]]
    from = "/*"
    to = "/"
    status = 200