[build]
    functions = "functions"
    base = "/"
    command = "npm run build"
[build.environment]
    NODE_VERSION = "22.12.0"
    GO_VERSION = "1.19.4"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[[redirects]]
    from = "/abend-fuer-die-moore-tickets"
    to = "https://cinema.kinokoni.ch/order/showtimes/50-685/seats"
    status = 302
    force = true
[[redirects]]
    from = "/abend-fuer-die-moore-wwf"
    to = "https://example-wwf-event.com"
    status = 302
    force = true
[[redirects]]
    from = "/*"
    to = "/"
    status = 200